<a href="https://colab.research.google.com/github/httpsdluc/eda-technical-practice/blob/main/customer_transactions_campagins_analysis/notebooks/customer_transactions_campagins_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
import numpy as np

In [33]:
df_campaign = pd.read_csv('data/Campaigns_from_Gmail.csv')
df_customers = pd.read_csv('data/Customers.csv')
df_transactions = pd.read_csv('data/Transactions_from_Gmail.csv')

1. how many unique customers are there?

In [ ]:
df_customers.head()

   customer_id  age  annual_income  spending_score
0         1000   56          61905              66
1         1001   69          41258              40
2         1002   46          89176              67
3         1003   32          57699              71
4         1004   60          46395              65

In [ ]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     200 non-null    int64
 1   age             200 non-null    int64
 2   annual_income   200 non-null    int64
 3   spending_score  200 non-null    int64
dtypes: int64(4)
memory usage: 6.4 KB

In [ ]:
df_customers.shape

(200, 4)

In [ ]:
df_customers.describe()

       customer_id        age  annual_income  spending_score
count   200.000000  200.00000     200.000000      200.000000
mean   1099.500000   43.42500   59990.615000       59.000000
std      57.879185   14.94191   15861.517489       18.380129
min    1000.000000   18.00000   16808.000000        8.000000
25%    1049.750000   31.00000   49401.000000       45.750000
50%    1099.500000   43.50000   59877.500000       61.000000
75%    1149.250000   56.00000   70807.500000       71.000000
max    1199.000000   69.00000  107805.000000      108.000000

In [ ]:
df_copy = df_customers['customer_id'].value_counts().reset_index()

In [ ]:
df_customers['customer_id'].nunique()

200

In [ ]:
df_copy

     customer_id  count
0           1000      1
1           1001      1
2           1002      1
3           1003      1
4           1004      1
..           ...    ...
195         1195      1
196         1196      1
197         1197      1
198         1198      1
199         1199      1

[200 rows x 2 columns]

In [ ]:
int(df_copy['count'].sum())

200

2. What is the average annual income?

In [ ]:
float(df_customers['annual_income'].mean())

59990.615

3. How many transactions are there?

In [ ]:
df_transactions.head()

   customer_id  transaction_amount
0         1000               11.51
1         1000               32.54
2         1000               61.43
3         1000              -18.18
4         1000               14.74

In [ ]:
df_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2327 entries, 0 to 2326
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         2327 non-null   int64
 1   transaction_amount  2327 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 36.5 KB

In [ ]:
df_transactions.shape

(2327, 2)

In [ ]:
df_transactions.describe()

       customer_id  transaction_amount
count  2327.000000         2327.000000
mean   1098.225183           31.179450
std      57.198700           21.968533
min    1000.000000          -37.170000
25%    1049.500000           16.270000
50%    1097.000000           31.640000
75%    1147.000000           46.080000
max    1199.000000          102.170000

In [ ]:
df_transactions['transaction_amount'].count()

np.int64(2327)

4. What is the percentage of people who recieved response?

In [ ]:
df_campaign.head()

   customer_id channel      offer_type  responded
0         1000    push  loyalty_points          1
1         1000     sms        cashback          0
2         1000    push  loyalty_points          1
3         1000   email  loyalty_points          1
4         1001   email          bundle          1

In [ ]:
df_campaign.describe()

       customer_id   responded
count   699.000000  699.000000
mean   1100.786838    0.399142
std      58.022069    0.490073
min    1000.000000    0.000000
25%    1051.000000    0.000000
50%    1101.000000    0.000000
75%    1153.000000    1.000000
max    1199.000000    1.000000

In [ ]:
sum_responses = int((df_campaign['responded'] == 1).sum())

In [ ]:
total_responses = int(df_campaign['responded'].count())

In [ ]:
percent_responses = (sum_responses/total_responses) * 100

In [ ]:
print(percent_responses)

39.91416309012876

5. What is the total spend per customer?

In [ ]:
df_transactions.head()

   customer_id  transaction_amount
0         1000               11.51
1         1000               32.54
2         1000               61.43
3         1000              -18.18
4         1000               14.74

In [ ]:
df_transactions.shape

(2327, 2)

In [ ]:
# making a dataframe that groups customer_id by transaction_amount sums
df_totalspend = df_transactions.groupby('customer_id')['transaction_amount'].sum().reset_index()

In [ ]:
# ensures all rows are shown
pd.set_option('display.max_rows', None)

In [ ]:
df_totalspend.head(200)

     customer_id  transaction_amount
0           1000              375.68
1           1001              404.54
2           1002              726.00
3           1003              344.94
4           1004              177.52
5           1005              374.00
6           1006              300.69
7           1007              288.17
8           1008              203.41
9           1009              214.62
10          1010              510.96
11          1011              426.66
12          1012              321.93
13          1013              310.58
14          1014              397.00
15          1015              516.30
16          1016              474.20
17          1017              202.33
18          1018              411.55
19          1019              444.92
20          1020              687.17
21          1021              549.11
22          1022              107.75
23          1023              814.10
24          1024              504.83
25          1025              478.62
26          1026              298.21
27          1027               22.24
28          1028              461.98
29          1029              450.17
30          1030              443.41
31          1031              472.93
32          1032              414.56
33          1033              579.74
34          1034              336.65
35          1035              257.42
36          1036              304.77
37          1037              502.52
38          1038              159.57
39          1039              331.89
40          1040              338.11
41          1041              214.36
42          1042              202.80
43          1043              643.31
44          1044              473.50
45          1045               93.73
46          1046              122.33
47          1047              451.33
48          1048              238.14
49          1049              366.87
50          1050              726.16
51          1051              638.14
52          1052              329.80
53          1053              199.59
54          1054              426.49
55          1055              221.30
56          1056              456.70
57          1057              470.16
58          1058              285.23
59          1059              568.89
60          1060              227.69
61          1061              163.88
62          1062              356.84
63          1063              106.45
64          1064              316.24
65          1065              343.65
66          1066              309.93
67          1067              468.52
68          1068              271.17
69          1069              142.94
70          1070              237.43
71          1071              163.80
72          1072              121.51
73          1073              190.31
74          1074              409.83
75          1075              393.39
76          1076              274.06
77          1077              306.49
78          1078              690.65
79          1079              408.79
80          1080              511.66
81          1081              228.24
82          1082              551.57
83          1083              788.56
84          1084              185.39
85          1085              223.22
86          1086              443.35
87          1087              190.67
88          1088              205.30
89          1089              320.18
90          1090              486.54
91          1091              285.41
92          1092              502.87
93          1093              519.06
94          1094              586.75
95          1095              239.83
96          1096              813.88
97          1097              589.65
98          1098              216.41
99          1099              149.77
100         1100              355.16
101         1101              246.55
102         1102              336.49
103         1103              521.86
104         1104              858.68
105         1105              375.35
106         1106              222.13
107         1107              260.19
108         1108              385.02
109         1109               31.79
110         1110              296.93
111         1111              160.59
112         1112              444.08
113         1113              295.77
114         1114              229.90
115         1115              156.46
116         1116              380.80
117         1117              134.91
118         1118              430.18
119         1119              220.53
120         1120              305.04
121         1121              780.40
122         1122              425.26
123         1123              309.95
124         1124               79.47
125         1125              565.07
126         1126              528.47
127         1127              114.09
128         1128              155.95
129         1129              259.80
130         1130              200.66
131         1131              588.97
132         1132              313.07
133         1133              298.47
134         1134              462.39
135         1135               71.11
136         1136              700.41
137         1137              475.55
138         1138              325.97
139         1139              350.06
140         1140              515.78
141         1141              239.04
142         1142              325.17
143         1143              421.74
144         1144              179.56
145         1145              221.11
146         1146              353.12
147         1147              198.22
148         1148              386.30
149         1149              302.29
150         1150              172.38
151         1151              261.19
152         1152              580.78
153         1153              341.88
154         1154              716.18
155         1155              270.03
156         1156              548.21
157         1157              329.10
158         1158              187.53
159         1159              339.03
160         1160              242.88
161         1161              594.85
162         1162              565.28
163         1163               75.42
164         1164              350.96
165         1165              450.20
166         1166              784.82
167         1167              401.33
168         1168              263.05
169         1169              483.53
170         1170              698.47
171         1171              213.09
172         1172              605.82
173         1173              685.19
174         1174              404.86
175         1175              434.82
176         1176              193.15
177         1177              597.76
178         1178              350.04
179         1179              385.92
180         1180              523.12
181         1181              398.16
182         1182              309.34
183         1183              484.32
184         1184              396.43
185         1185              624.65
186         1186              199.05
187         1187              310.28
188         1188              335.65
189         1189              140.45
190         1190               25.78
191         1191              144.67
192         1192              383.70
193         1193              321.91
194         1194              172.21
195         1195              736.51
196         1196              335.90
197         1197               64.87
198         1198              121.19
199         1199              190.32

6. Is income correlated with total spending?

In [ ]:
df_merge_totalspending = pd.merge(df_customers, df_totalspend, on = 'customer_id', how = 'inner')

In [ ]:
df_merge_totalspending.head()

   customer_id  age  annual_income  spending_score  transaction_amount
0         1000   56          61905              66              375.68
1         1001   69          41258              40              404.54
2         1002   46          89176              67              726.00
3         1003   32          57699              71              344.94
4         1004   60          46395              65              177.52

7. Which channel has the highest response rate?

8. Do high spending_score customers actually spend more?

9. Which offer_type performs best?

10. Do customers with more transactions respond more to campaigns?

11. Build customer segments (e.g. low / mid / high income). Compare:
avg spend
response rate

12. Which combination performs best? (channel + offer_type)

13. Find “high-value but low-response” customers

14. Outlier detection:

15. Build a simple model: predict responded
Features:
income
spending_score
avg transaction
transaction count